---
development:
  dialect: "sqlite3"
  database: "/Users/jah/Projects/bp/api/bp_development.sqlite"

test:
  dialect: "sqlite3"
  database: "/tmp/bp_test.sqlite"

production:
  dialect: "sqlite3"
  database: "/Users/jah/Projects/bp/api/bp_production.sqlite"
