---
development:
  dialect: postgres
  database: bp_dev
  user: dev
  password: dev
  host: 127.0.0.1
  pool: 5

test:
  url: {{envOr "DATABASE_URL" "postgres://dev:dev@127.0.0.1:5432/bp_test"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://dev:dev@127.0.0.1:5432/bp_prod"}}
