---
development:
  dialect: postgres
  database: bp_dev
  user: jah
  host: 127.0.0.1
  pool: 5

test:
  dialect: postgres
  database: bp_test
  user: jah
  host: 127.0.0.1
  pool: 5

production:
  dialect: postgres
  database: bp_prod
  user: jah
  host: 127.0.0.1
  pool: 5
